### ISSUE TITLE
Numero static de siguiente venta

### ISSUE THREAD

**Issue by DamianViera** [lucaeLeleiva/Obligatorio2C-#15]
Como hago para  traer al ToString de Empresa el static numeroDeSiguienteVenta (q esta en la clase venta)???

**Comment by lucaeLeleiva** [comment]
Venta.NumeroDeSiguienteVenta

**Comment by lucaeLeleiva** [comment]
PD. si consideras que el issue fue resuelto abajo de los comentarios deberia de aparecer Close, ahi lo cerras y sabemos que quedo solucionado.

**Comment by DamianViera** [comment]
Ya habia probado con eso pero no funciona

**Comment by lucaeLeleiva** [comment]
Ya creaste la propiedad y la hiciste public?

**Comment by DamianViera** [comment]
Nop, como se iba a modificar solo en el constructor el numero no le hice propiedad, ahora la hago y pruebo

**Comment by lucaeLeleiva** [comment]
Podes ponerle solo get para poder leerlo de cualquier lado y no escribir el set asi no pueden cambiarlo de afuera
