### ISSUE TITLE
Propiedad Total (Me devuelve 0)

### ISSUE THREAD

**Issue by DamianViera** [lucaeLeleiva/Obligatorio2C-#17]
public double Total
        {
            set
            {
                //Chequeo si se aplicara el descuento
                if ((fechaDePago-fechaDeVenta).Days<=30)// Si la fecha de pago - la fecha de venta es menos que 30 aplica dcto
                {
                    double subTotal = producto.Precio * cantidad;
                    double descuento = (cliente.Descuento / 100) * subTotal;
                    total = subTotal-descuento;
                }
                else
                { total = producto.Precio * cantidad; }//Si no paga antes del mes de la fecha de venta, no hay descuento
            }
            get
            { return total; }
        }

**Comment by DamianViera** [comment]
Es la propiedad Total de la clase Venta
Cuano hago el venta.ToString() el total me muestra 0
Claramente la estoy cagando en algo, vos lo ves?

**Comment by lucaeLeleiva** [comment]
producto.Precio y cliente.Descuento te devuelven algo? No se exactamente como lo tenes creado pero capaz que pedis producto.Precio y/o cliente.Descuento sin tenerlos asignados y como son ints o doubles si no lo asignas son 0. y si alguno te devuelve 0 como los estas multiplicando te devolveria 0.

**Comment by DamianViera** [comment]
Cliente c1 = new Cliente("4139183",10, "Rivera 3705", "099911191");//10 es el descuento
Producto p1 = new Producto("77512485930", new DateTime(2016,08,19), "Alfajor", 20);//20 es el precio
Venta v1 = new Venta(c1, p1, new DateTime(2016, 10, 09), new DateTime(2016, 12, 09), 3,0);//3 es cantidad

**Comment by DamianViera** [comment]
public Venta(Cliente pCliente, Producto pProducto, DateTime pFechaDeVenta, DateTime pFechaDePago, int pCantidad, int pNumeroDeVenta)
        {
            Cliente = pCliente;
            Producto = pProducto;
            FechaDeVenta = pFechaDeVenta;
            FechaDePago = pFechaDePago;
            Cantidad = pCantidad;
            NumeroDeVenta = pNumeroDeVenta;
            numeroDeSiguienteVenta++;//Autogenero el numero de ventas
        }

**Comment by lucaeLeleiva** [comment]
Ahh claro, no lo asignas. Lo que quedaria mejor en mi opinion, es que lo que tenes en el set de total, lo muevas a metodo private double Total(){codigo del set} y al final del constructor lo llames.
Y el set enrealidad como seria autogenerado no lo hagas.

**Comment by DamianViera** [comment]
Ya esta era el constructor

public Venta(Cliente pCliente, Producto pProducto, DateTime pFechaDeVenta, DateTime pFechaDePago, int pCantidad, int pNumeroDeVenta)
        {
            Cliente = pCliente;
            Producto = pProducto;
            FechaDeVenta = pFechaDeVenta;
            FechaDePago = pFechaDePago;
            Cantidad = pCantidad;
            NumeroDeVenta = pNumeroDeVenta;
            Total = total;//Me faltaba el total aca!!
            numeroDeSiguienteVenta++;//Autogenero el numero de ventas
        }

**Comment by lucaeLeleiva** [comment]
Llegaste a leer lo ultimo que puse?

**Comment by DamianViera** [comment]
Nop, sorry,ahora lo veo
