### ISSUE TITLE
Empresa

### ISSUE THREAD

**Issue by lucaeLeleiva** [lucaeLeleiva/Obligatorio2C-#20]
Refactorizando Empresa me empezaron a surgir dudas. Si la propiedad (las listas) es privada es lo mismo que no este, cierto?
Lo otro, si el nombre no quiero que sea otra cosa que no sea "Comida Rica" lo mejor es sacar el setter y ya era, no?

**Comment by lucaeLeleiva** [comment]
Se me ocurren dos cosas, usar "Comida Rica" como contraseña(Es decir si en la pagina de inicio no escribe eso decirle que el nombre es incorrecto y no dejarlo avanzar), o forzar a que ponga lo que ponga meterle "Comida Rica" en la variable 'nombre'.

**Comment by bios2016** [comment]
como si fuera usuario?

**Comment by lucaeLeleiva** [comment]
Claro. Algo asi si.

**Comment by bios2016** [comment]
eso se haría en el default? no?

**Comment by lucaeLeleiva** [comment]
Te referis a default.aspx ? Si seria ahi.

**Comment by DamianViera** [comment]
Para mi:
-Le pedimos el nombre
-Ingresa el nombre y si NO es "Comida Rica" mensaje de error (Como esta hecho)

Yo le dejaria el set y lo haria de esa forma

**Comment by DamianViera** [comment]
Con respecto a lo de las listas, decis de sacar las propiedades??
Asi como esta no funciona o algo?
O decis que estan de mas?

**Comment by lucaeLeleiva** [comment]
Con respecto al nombre, me parece lo mejor si, con respecto a las listas claro, para mi estan de mas por que no se usan de afuera, pero luego en el contructor vi que lo mejor seria hacer una modificacion que hice que seria que solo se puede ver en la clase y solo se puede settear a una lista vacia, despues cuando suba lo que he hecho vemos si les gusta.

**Comment by bios2016** [comment]
de acuerdo con lo del nombre... lo de las listas.. no se puede hacer lo mismo q con lo del nombre? pero q quede registrado quien fue que lo modifico? osea, si es la pag q modifican los de la empresa nomas... q el gerente tenga una contraseña, el contador otra, y bla bla, (q sean 4 personas q puedan acceder nomas) y cuando van a modificar borrar, agregaretc, q pongan eso pero q se guarde la contraseña, asi saben quien fue el ultimo en entrar, no se si sirve de algo lo q dije.. pero ta
