### ISSUE TITLE
Venta

### ISSUE THREAD

**Issue by lucaeLeleiva** [lucaeLeleiva/Obligatorio2C-#21]
En la clase venta, creo que es la que creo Damian, por que no se puede settear fechaDeVenta a otro dia que no sea el actual?

**Comment by DamianViera** [comment]
Porque me parece que "Es como deberia de funcionar un sistema de ventas".
La venta NO se puede realizar en un dia pasado, y en uno futuro tampoco, osea, una venta SOLO se efectua el mismo dia, que se le ponga otra fecha "para mi" generaría conflicto de facturacion

**Comment by DamianViera** [comment]
En cualquier sistema de facturacion la fecha la carga el sistema por si solo, NO permitiendo al usuario modifcar la fecha de una venta, justamente porque en la facturacion no se puede ir para atras ni para adelante, las facturas deben de llevar un orden.
Ej
Factura N°1 30/7
Factura N°2 30/7
Factura N°3 30/7
Factura N°4 27/7

En este ejemplo la ultima factura genera una incoherencia en la facturacion de la empresa.

**Comment by lucaeLeleiva** [comment]
Esta bien, estuve leyendo la letra y como no se debe de modificar la venta que solo se pueda y deba de ingresar la fecha actual esta bien.
