### ISSUE TITLE
Empresa

### ISSUE THREAD

**Issue by lucaeLeleiva** [lucaeLeleiva/Obligatorio2C-#30]
En el ultimo cambio que se realizo en empresa, porque pasaste a public los list? De ese cambio me quedo la duda, los demás cambios me parecieron buenos, mejoraron la legibilidad del código y arreglaste ese error que no había visto en IngresarVenta.

**Comment by DamianViera** [comment]
Las cambie a public porque si no son publicas no me dejaba usarlas desde la pagina MantenimientoClientes.aspx , solo cuando cambie eso fue que pude hacer funcionar las operaciones que usan las listas.

**Comment by lucaeLeleiva** [comment]
Encontre por que daba null el list.count
Estaban mal inicializadas las listas en la propiedad, decia:
value=listxxxxx;
En vez de:
listxxxx=value;
