### ISSUE TITLE
Venta Formulario.

### ISSUE THREAD

**Issue by lucaeLeleiva** [lucaeLeleiva/Obligatorio2C-#33]
Consideran que en el formulario de venta es necesario pedir la fecha de venta? Ya que la misma esta limitada por codigo a ser la de hoy.

**Comment by DamianViera** [comment]
Pa mi seria al pedo pedirlo, yo por ejemplo me acuerdo del sistema de facturacion con el que trabajaba antes y NO habia que poner nunca la fecha de la venta porque siempre es la del dia que corre.

**Comment by DamianViera** [comment]
Igual ya me lo anote para preguntar el lunes

**Comment by lucaeLeleiva** [comment]
Ahi va, cuando lo estaba haciendo y tenia que poner un rango de fechas me di cuenta que estaba medio al pedo asi que lo saque. El Lunes vemos igual.
